### ISSUE TITLE
(1.12) Poof! Crash...

### ISSUE THREAD

**Issue by Migmag789** [TheDragonTeam/TheDragonLib#2]
A brand new crash, with DragonLib.
[crash-2017-06-30_17.33.28-client.txt](https://github.com/TheDragonTeam/TheDragonLib/files/1115743/crash-2017-06-30_17.33.28-client.txt)

**Comment by Moritz30** [comment]
This is not related to TheDragonLib. Please report to [ArmorPlus](https://github.com/thedragonteam/armorplus) using the [Issue Template](https://raw.githubusercontent.com/TheDragonTeam/ArmorPlus/kotlin/ISSUE_TEMPLATE.md)

**Comment by sokratis12GR** [comment]
https://github.com/TheDragonTeam/ArmorPlus/issues/154
