### ISSUE TITLE
Server Crash With TheDragonLib

### ISSUE THREAD

**Issue by IchigoGames** [TheDragonTeam/TheDragonLib#3]
Server Crash
Minecraft 1.12.1
thedragonlib-1.12.1-4.2.0
armorplus-1.12-11.5.1.16-alpha
crash report https://pastebin.com/jZhMNbHs

**Comment by sokratis12GR** [comment]
Thanks for the report!
Hopefully fixed in version 1.12.1-5.0.0

**Comment by sokratis12GR** [comment]
https://minecraft.curseforge.com/projects/thedragonlib/files/2468908 should have fixed the issue, let me know if it did so... thanks!

**Comment by IchigoGames** [comment]
yap its fixed 👍
